#!/usr/bin/env bash
# Refresh repo default-app policy (config/duti) from current Launch Services handlers.
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
DOTFILES="${DOTFILES:-$(cd -- "$SCRIPT_DIR/.." && pwd -P)}"
OUTPUT="${1:-$DOTFILES/config/duti}"
SOURCE="${DUTI_SOURCE:-$OUTPUT}"

if ! command -v duti >/dev/null 2>&1; then
  echo "duti is not installed; run: make brew" >&2
  exit 1
fi

# Prefer extensions already listed in config/duti so refresh stays focused and
# low-noise. Fall back to common developer/document extensions.
default_extensions=(
  applescript c cc cpp css env go h html js json jsx lua mjs md pdf png jpg jpeg gif webp
  py rb rs sh sql toml ts tsx txt xml yaml yml
)
# HTTPS is intentionally omitted: on this macOS/duti combination, direct
# `duti -s <bundle> https` returns error -54 for every tested browser.
default_schemes=(http mailto webcal)

extensions=()
utis=()
if [ -f "$SOURCE" ]; then
  while read -r bundle target _rest; do
    case "${bundle:-}" in ''|\#*) continue ;; esac
    case "${target:-}" in
      .*) extensions+=("${target#.}") ;;
      *.*) utis+=("$target") ;;
    esac
  done < "$SOURCE"
fi
if [ "${#extensions[@]}" -eq 0 ]; then
  extensions=("${default_extensions[@]}")
fi

unique_lines() {
  printf '%s\n' "$@" | awk 'NF && !seen[$0]++'
}

deduped_extensions=()
while IFS= read -r ext; do
  [ -n "$ext" ] && deduped_extensions+=("$ext")
done < <(unique_lines "${extensions[@]}")
extensions=("${deduped_extensions[@]}")

tmp="$(mktemp -t duti.capture.XXXXXX)"
trap 'rm -f "$tmp"' EXIT

{
  echo "# Default application mappings (repo policy for the Brewfile app set)."
  echo "# Generated by scripts/capture-duti.sh on $(date '+%Y-%m-%d %H:%M:%S %Z')."
  echo "# Format: bundle-id extension-or-UTI-or-url-scheme [role]"
  echo
  echo "# File extensions"
} > "$tmp"

captured=0
for ext in "${extensions[@]}"; do
  lines=()
  while IFS= read -r line; do
    lines+=("$line")
  done < <(duti -x "$ext" 2>/dev/null || true)
  bundle_id="${lines[2]:-}"
  if [ -n "$bundle_id" ]; then
    if [ "$ext" = "env" ]; then
      # duti maps .env to a dynamic UTI and rejects explicit roles for it.
      printf '%s .%s\n' "$bundle_id" "$ext" >> "$tmp"
    else
      printf '%s .%s all\n' "$bundle_id" "$ext" >> "$tmp"
    fi
    captured=$((captured + 1))
  fi
done

{
  echo
  echo "# Uniform Type Identifiers"
} >> "$tmp"

while IFS= read -r uti; do
  [ -n "$uti" ] || continue
  bundle_id="$(duti -d "$uti" 2>/dev/null | head -n 1 || true)"
  if [ -n "$bundle_id" ]; then
    printf '%s %s all\n' "$bundle_id" "$uti" >> "$tmp"
    captured=$((captured + 1))
  fi
done < <(unique_lines "${utis[@]}")

{
  echo
  echo "# URL schemes"
} >> "$tmp"

for scheme in "${default_schemes[@]}"; do
  bundle_id="$(duti -d "$scheme" 2>/dev/null | head -n 1 || true)"
  if [ -n "$bundle_id" ]; then
    # URL schemes must be role-less. With a role, duti treats them as dynamic UTIs.
    printf '%s %s\n' "$bundle_id" "$scheme" >> "$tmp"
    captured=$((captured + 1))
  fi
done

mkdir -p "$(dirname "$OUTPUT")"
mv "$tmp" "$OUTPUT"
trap - EXIT

echo "Captured $captured default app mapping(s) → $OUTPUT"
