
# this file is read when starting new login shell, before .zshrc

# ----- Monokai Pro
# set initial shell level
export INIT_SHELL_LEVEL=$SHLVL

# encoding
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# history
export HISTFILE=$HOME/.zsh_history
export HISTSIZE=10000
export SAVEHIST=10000

# path variable
export PATH=/usr/local/bin:/usr/local/sbin:"$PATH"

# ----- Mine
[ -x /opt/homebrew/bin/brew ] && eval "$(/opt/homebrew/bin/brew shellenv)"
export PATH="/Applications/Sublime Text.app/Contents/SharedSupport/bin:$PATH"
